### ISSUE TITLE
Defining data structure for LQ dynamic optimization

### ISSUE THREAD

**Issue by sshin23** [MadNLP/DynamicNLPModels.jl#2]
We should define the following data structure for LQ dynamic optimization
```julia
abstract type AbstractDynamicData{T,S} end

struct LQDynamicData{T,S,M} <: AbstractDynamicData{T,S}
s0::S
A::M
B::M
Q::M
R::M
Qf::M
# etc
end

abstract type AbstractDynamicModel{T,S} <: QuadraticModels.AbstractQuadraticModel{T, S} end

mutable struct LQDynamicModel{T, S, M1, M2, M3} <:  AbstractDynamicModel{T,S} 
  meta::NLPModelMeta{T, S}
  counters::Counters
  data::QPData{T, S, M1, M2}
  dynamic_data::LQDynamicData{T,S,M3}
  condense::Bool
end
```

and 
- define a constructor for `LQDynamicData`
- replace the current `build_QM` with `LQDynamicModel(::LQDynamicData{T,S,M}; condense = false) where {T,S,M}`
- define dynamic optimization-specific APIs such as `get_s0` and `set_s0!`

**Comment by dlcole3** [comment]
Since we want functions such as `set_s0!`, should `LQDynamicData{T,S,M}` be a mutable struct rather than just a struct?

**Comment by dlcole3** [comment]
Also, do you want me to get rid of `build_H` and `build_J` as well and just implement them internally within `LQDynamicModel(::LQDynamicData{T,S,M}; condense = false)`? Or should I leave them as stand alone functions?

**Comment by sshin23** [comment]
`set_s0!` should only modify the entry of `lq_dyn_data.s0`, so the `LQDynamicData` doesn't need to be mutable. But if you find it is more proper to make it a `mutable struct`, go ahead and make it mutable (there's no particular reason for it to be immutable either).

**Comment by sshin23** [comment]
we can keep `_build_H` and `_build_J `, but they should be called internally within `LQDynamicModel(::LQDynamicData{T,S,M}; condense = false)`

**Comment by dlcole3** [comment]
What all should our API be able to do? Right now, I am just building functions to get and set the entries of `LQDynamicData` (i.e., s0, A, B, R, Q, sl, su, ul, uu). My `set!` functionalities can also either redefine the matrix entirely or just modify an entry of the matrix. Is there more that I should include within the API functionalities?

**Comment by sshin23** [comment]
for now that should be enough, but if there's anything you feel like it will be necessary for the user, you can add them. Those APIs should always change the entry, not the arrays themselves
