### ISSUE TITLE
Hessian bug fix

### ISSUE THREAD

**Issue by sshin23** [MadNLP/DynamicNLPModels.jl#4]
Normally, MadNLP shouldn't regularize the problem for convex QPs, but it is regularizing this problem. This is an indication of a potential bug. This should be root-caused and fixed
https://github.com/MadNLP/DynamicNLPModels.jl/runs/6838395675?check_suite_focus=true#step:5:656

**Comment by dlcole3** [comment]
@sshin23, I think the reason for this error is that I have a a $u_N$ variable defined, which results in an empty column in the Jacobian and an empty row and column in the Hessian. There is no need for a $u_N$ decision variable, is there? I don't see it coming up in any of the constraints of the Jerez et al. paper. If so, I will go ahead and remove it.

**Comment by sshin23** [comment]
yes, empty variable causes an inssue
