### ISSUE TITLE
Add support for sparse `Q,R,A,B`

### ISSUE THREAD

**Issue by sshin23** [MadNLP/DynamicNLPModels.jl#6]
Currently we do not take into account the sparsity in `Q,R,A,B`. The hessian/Jacobian should respect the sparsity of `Q,R,A,B` given by the user. A specialized `_build_H` and `_build_J` function should be added via multiple dispatch

**Comment by dlcole3** [comment]
Should I assume that Q and R are both sparse in the specialized `_build_H` function? Or should I create multiple functions so that Q can be spares while R is dense or vice versa?

**Comment by sshin23** [comment]
@dlcole3 should make it all sparse. We have enforced they have the same type in `LQDynamicData`

**Comment by sshin23** [comment]
closing it as the current approach preserves the sparsity. Thanks @dlcole3 for the corretion
